language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator
script:
- make
notifications:
  email: false
  slack:
    secure: Ara4DAGNXAD3qaXDFRb3uHHpwqutXwKGocu02uKTYSH3sjmrs2XGOmOHcVNxUjXCFwXGzXyNsnBxNZboZJUYW3tiDF4Xi003+WSmR7PKZCwdrSgvEIgJH2Kcl4dQn55EEdafVi0+gCkXiqh1iICnHhIkRZnI4zm/Mdl32wVTifTDwzsLDvX8H47issoPJguB4+3HZT2EcI/6lRhyxGw8kk3Pye0RSmfNYyz3YOibE20//3AePksEWMVkIi0gDVqQssZZiOfUvAegrWtJEarUO0xKK8zda+FwiePzw4DZJqv0ObEwVITN/OgTuMSztFGV/BMS9gTW5MB994BU4k3FRUR8qjNVbLA9zDMuVvXztayvKpx13LH19/AkIDXjWDY31vBSKTIj23uLORLjLwYgGJjZxT5t4cUwPnkpz9gB4Jo6RSKadGycLIZSuERE/3zpKOnUlfmU892PPKXITpt0skvgbWnpiZw/2T45A2aK3g4UgoPsujja9TqZ4pegAy6rtf1xSiJNwvsFBuPn78qxKAySbANVubWPKIQpnwZBk8X2AM0AvGjX5CZOm/vbSCC+xj2JRA0P9YriNRkrvy/SAvdlqDO9HditWsFyiHU/12PUvU5ewgJmxl4UB5LFcNbzvGioEQzsZakcJuoHxp9uTSRpj+jhVk5ELaBihc58m04=
